### ISSUE TITLE
Love letter from Thermondo

### ISSUE THREAD

**Issue by codingjoe** [mark-adams/pytest-test-groups#1]
:love_letter:

Hi @mark-adams,

thanks for providing this great package. We started looking for this just today, just thought we would have to built it ourself. Then we stumbled on your package working perfectly :) 

If we would started our search yesterday, we wouldn't have found it I guess.

Thanks from the entire [Thermondo](https://github.com/Thermondo/) dev team, that no longer has to wait an hour for our builds to pass!

**Comment by mark-adams** [comment]
That's awesome!!! I'm so glad it could help you guys!! :smile:
